parameters:
  project:
    name: mortgage-credit-risk

  logging:
    enabled: true
    level: INFO
    color: true

  reporting:
    skip: true

  data:
    data_provider: freddie_mac
    vintage: 2019
    id_col: "loan_id"
    time: "period"
    ingestion:
      skip: true
      chunksize: 2500000
    preprocess:
      skip: true 
  modelling:
    skip: true
    vintages_train:
      - 2015
      - 2016
      - 2017
    vintages_oot:
      - 2018
      - 2019
    validation_size : 0.2
    random_state: 42
    stratify: true

  target:
    name : ever_90dpd_24m
    serious_delinquency_threshold: 3
    max_eligible_start_age: 1
    horizon_months: 24
    voluntary_payoffs_zbc: "01"
